name: emsdk_build
on: [workflow_dispatch]

jobs:
  # Build job. Builds app for web with emsdk
  build-android:
    name: Build for Emscripten
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
            WD=$(pwd)
            python3 -V
            echo $WD
            clang --version | head -n 1
            echo
            grep "^Pkg.Revision =" ${ANDROID_HOME}/ndk-bundle/source.properties
            cd $GITHUB_WORKSPACE/..
            export PROJECT=$(basename $(find $GITHUB_WORKSPACE/static|grep py$) .py)
            git clone https://github.com/pmp-p/python-wasm-plus.git
            ln -s $GITHUB_WORKSPACE python-wasm-plus/demos/$PROJECT
            cd python-wasm-plus
            bash ./python-wasm-plus.sh
            bash ./buildapp.sh templates/no-worker-fs demos/$PROJECT demo
            cd $GITHUB_WORKSPACE/../python-wasm-plus/demos/$PROJECT
            echo "==================="
            pwd
            echo "==================="
            cd $GITHUB_WORKSPACE/../python-wasm-plus/build/demo
            pwd
            ls -al
            du -hs *
